const {chromium}=require('playwright');const http=require('http');const fs=require('fs');
const srv=http.createServer((q,r)=>{r.writeHead(200,{'content-type':'text/html'});r.end(fs.readFileSync(process.argv[2]));}).listen(8792);
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
 const p=await b.newPage();const errs=[];p.on('pageerror',e=>errs.push(String(e)));
 await p.addInitScript({path:__dirname+'/mock3.js'});
 await p.addInitScript(()=>{try{localStorage.setItem('evolve-toured','1')}catch(e){}});
 await p.goto('http://localhost:8792/');await p.waitForTimeout(2000);
 const R=await p.evaluate(async()=>{const sl=ms=>new Promise(r=>setTimeout(r,ms));
  let cap=null; window.confirm2=(t,b,go)=>{cap={go};};
  S.tour=true; clientEdit(S.clients.c1); await sl(50);
  const bs=[...document.querySelectorAll('button')].filter(x=>x.textContent.trim()==="Delete"); bs[bs.length-1].click(); cap&&cap.go(); await sl(120);
  const r={stored:!!__ST.clients.c1,onScreen:!!S.clients.c1,bin:Object.keys(__ST.bin||{}).length};
  S.tour=false; return r;});
 console.log(JSON.stringify(R),errs);await b.close();srv.close();})();
